UUID power gen; config option to generate powers based off of player's UUID
legobmw99/Allomancy pull request #70
Opened 2022-01-12 19:59 UTC by Roseplate

I also snuck in a change to the readme (V_4_Vicegod to Roseplate)

2022-01-12 22:09 UTC, legobmw99 requested changes
Thanks for putting this together. I'd appreciate if you could change these, more about style than anything

2022-01-12 22:09 UTC, legobmw99 commented on src/main/java/com/legobmw99/allomancy/modules/powers/CommonEventHandler.java
> +    public static int randomNumbGen(Player player) {
I would prefer if this logic all just got moved inside the conditional. It doesn't get reused anywhere, so I don't think it needs to be a function

2022-01-12 22:09 UTC, legobmw99 commented on src/main/java/com/legobmw99/allomancy/modules/powers/CommonEventHandler.java
> +    public static int HexToDecimal(String s){
Same with this

2022-01-13 10:50 UTC, Roseplate commented
done and done, I think, not super used to github

2022-01-13 15:51 UTC, merged

2022-01-13 15:52 UTC, legobmw99 commented
Thanks!